// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // Use iOS config as a fallback for macOS if available, often works for Firebase
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'Firebase has not been configured for this platform (${defaultTargetPlatform.name}). '
          'Please run "flutterfire configure" to add support.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mX4ZxNrKwO95mREdOrKqxzrRgjSDiTk',
    appId: '1:231411507802:android:86f81331d8031d468f6e63',
    messagingSenderId: '231411507802',
    projectId: 'smart-clinic-90c51',
    storageBucket: 'smart-clinic-90c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIsj6pKYljdf6KrhXauO1kKq-5dilPR2E',
    appId: '1:231411507802:ios:a1714fa89f35b3988f6e63',
    messagingSenderId: '231411507802',
    projectId: 'smart-clinic-90c51',
    storageBucket: 'smart-clinic-90c51.firebasestorage.app',
    iosBundleId: 'com.example.smartClinicBooking',
    iosClientId: '231411507802-1rs6e29cma20me3krvhvujefugnvej2l.apps.googleusercontent.com',
  );

}